/*
 * BIM-Portal REST-API
 * Dies ist die Dokumentation der REST-Endpunkte, die sowohl öffentliche als auch private Informationselemente abrufen können. Authentifizierung ist für den Zugriff auf private Ressourcen erforderlich. Die Endpunkte können auf dieser Seite getestet werden.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.bimportal.client.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;
import org.hibernate.validator.constraints.*;

/** AIADomainSpecificModelPublicDto */
@JsonPropertyOrder({
  AIADomainSpecificModelPublicDto.JSON_PROPERTY_ID,
  AIADomainSpecificModelPublicDto.JSON_PROPERTY_CREATED_DATE,
  AIADomainSpecificModelPublicDto.JSON_PROPERTY_DATE_OF_ACTIVATION,
  AIADomainSpecificModelPublicDto.JSON_PROPERTY_DATE_OF_LAST_CHANGE,
  AIADomainSpecificModelPublicDto.JSON_PROPERTY_DATE_OF_REVISION,
  AIADomainSpecificModelPublicDto.JSON_PROPERTY_DATE_OF_VERSION,
  AIADomainSpecificModelPublicDto.JSON_PROPERTY_DATE_OF_DEACTIVATION,
  AIADomainSpecificModelPublicDto.JSON_PROPERTY_GUID,
  AIADomainSpecificModelPublicDto.JSON_PROPERTY_NAME,
  AIADomainSpecificModelPublicDto.JSON_PROPERTY_DESCRIPTION,
  AIADomainSpecificModelPublicDto.JSON_PROPERTY_ORGANISATION_ID,
  AIADomainSpecificModelPublicDto.JSON_PROPERTY_ORGANISATION_NAME,
  AIADomainSpecificModelPublicDto.JSON_PROPERTY_VERSION_NUMBER,
  AIADomainSpecificModelPublicDto.JSON_PROPERTY_REVISION_NUMBER,
  AIADomainSpecificModelPublicDto.JSON_PROPERTY_BUILD_NUMBER,
  AIADomainSpecificModelPublicDto.JSON_PROPERTY_EXPORT_FORMATS,
  AIADomainSpecificModelPublicDto.JSON_PROPERTY_TEMPLATE_TYPE,
  AIADomainSpecificModelPublicDto.JSON_PROPERTY_CHAPTERS,
  AIADomainSpecificModelPublicDto.JSON_PROPERTY_LOINS,
  AIADomainSpecificModelPublicDto.JSON_PROPERTY_DATA_FORMATS
})
@jakarta.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2025-09-03T22:05:51.794303+02:00[Europe/Berlin]",
    comments = "Generator version: 7.9.0")
public class AIADomainSpecificModelPublicDto {
  public static final String JSON_PROPERTY_ID = "id";
  private UUID id;

  public static final String JSON_PROPERTY_CREATED_DATE = "createdDate";
  private OffsetDateTime createdDate;

  public static final String JSON_PROPERTY_DATE_OF_ACTIVATION = "dateOfActivation";
  private OffsetDateTime dateOfActivation;

  public static final String JSON_PROPERTY_DATE_OF_LAST_CHANGE = "dateOfLastChange";
  private OffsetDateTime dateOfLastChange;

  public static final String JSON_PROPERTY_DATE_OF_REVISION = "dateOfRevision";
  private OffsetDateTime dateOfRevision;

  public static final String JSON_PROPERTY_DATE_OF_VERSION = "dateOfVersion";
  private OffsetDateTime dateOfVersion;

  public static final String JSON_PROPERTY_DATE_OF_DEACTIVATION = "dateOfDeactivation";
  private OffsetDateTime dateOfDeactivation;

  public static final String JSON_PROPERTY_GUID = "guid";
  private UUID guid;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_ORGANISATION_ID = "organisationId";
  private UUID organisationId;

  public static final String JSON_PROPERTY_ORGANISATION_NAME = "organisationName";
  private String organisationName;

  public static final String JSON_PROPERTY_VERSION_NUMBER = "versionNumber";
  private Long versionNumber;

  public static final String JSON_PROPERTY_REVISION_NUMBER = "revisionNumber";
  private Long revisionNumber;

  public static final String JSON_PROPERTY_BUILD_NUMBER = "buildNumber";
  private Long buildNumber;

  public static final String JSON_PROPERTY_EXPORT_FORMATS = "exportFormats";
  private Set<String> exportFormats = new LinkedHashSet<>();

  /** Gets or Sets templateType */
  public enum TemplateTypeEnum {
    COMPLETED_TEMPLATE("COMPLETED_TEMPLATE"),

    UNCOMPLETED_TEMPLATE("UNCOMPLETED_TEMPLATE"),

    PROJECT_TEMPLATE("PROJECT_TEMPLATE");

    private String value;

    TemplateTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TemplateTypeEnum fromValue(String value) {
      for (TemplateTypeEnum b : TemplateTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TEMPLATE_TYPE = "templateType";
  private TemplateTypeEnum templateType;

  public static final String JSON_PROPERTY_CHAPTERS = "chapters";
  private List<@Valid ChapterPublicReference> chapters = new ArrayList<>();

  public static final String JSON_PROPERTY_LOINS = "loins";
  private List<@Valid LoinPublicReference> loins = new ArrayList<>();

  public static final String JSON_PROPERTY_DATA_FORMATS = "dataFormats";
  private Set<LOINPublicDtoDataFormatsInner> dataFormats = new LinkedHashSet<>();

  public AIADomainSpecificModelPublicDto() {}

  public AIADomainSpecificModelPublicDto id(UUID id) {

    this.id = id;
    return this;
  }

  /**
   * Get id
   *
   * @return id
   */
  @jakarta.annotation.Nullable
  @Valid
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getId() {
    return id;
  }

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(UUID id) {
    this.id = id;
  }

  public AIADomainSpecificModelPublicDto createdDate(OffsetDateTime createdDate) {

    this.createdDate = createdDate;
    return this;
  }

  /**
   * Get createdDate
   *
   * @return createdDate
   */
  @jakarta.annotation.Nullable
  @Valid
  @JsonProperty(JSON_PROPERTY_CREATED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getCreatedDate() {
    return createdDate;
  }

  @JsonProperty(JSON_PROPERTY_CREATED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedDate(OffsetDateTime createdDate) {
    this.createdDate = createdDate;
  }

  public AIADomainSpecificModelPublicDto dateOfActivation(OffsetDateTime dateOfActivation) {

    this.dateOfActivation = dateOfActivation;
    return this;
  }

  /**
   * Get dateOfActivation
   *
   * @return dateOfActivation
   */
  @jakarta.annotation.Nullable
  @Valid
  @JsonProperty(JSON_PROPERTY_DATE_OF_ACTIVATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getDateOfActivation() {
    return dateOfActivation;
  }

  @JsonProperty(JSON_PROPERTY_DATE_OF_ACTIVATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateOfActivation(OffsetDateTime dateOfActivation) {
    this.dateOfActivation = dateOfActivation;
  }

  public AIADomainSpecificModelPublicDto dateOfLastChange(OffsetDateTime dateOfLastChange) {

    this.dateOfLastChange = dateOfLastChange;
    return this;
  }

  /**
   * Get dateOfLastChange
   *
   * @return dateOfLastChange
   */
  @jakarta.annotation.Nullable
  @Valid
  @JsonProperty(JSON_PROPERTY_DATE_OF_LAST_CHANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getDateOfLastChange() {
    return dateOfLastChange;
  }

  @JsonProperty(JSON_PROPERTY_DATE_OF_LAST_CHANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateOfLastChange(OffsetDateTime dateOfLastChange) {
    this.dateOfLastChange = dateOfLastChange;
  }

  public AIADomainSpecificModelPublicDto dateOfRevision(OffsetDateTime dateOfRevision) {

    this.dateOfRevision = dateOfRevision;
    return this;
  }

  /**
   * Get dateOfRevision
   *
   * @return dateOfRevision
   */
  @jakarta.annotation.Nullable
  @Valid
  @JsonProperty(JSON_PROPERTY_DATE_OF_REVISION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getDateOfRevision() {
    return dateOfRevision;
  }

  @JsonProperty(JSON_PROPERTY_DATE_OF_REVISION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateOfRevision(OffsetDateTime dateOfRevision) {
    this.dateOfRevision = dateOfRevision;
  }

  public AIADomainSpecificModelPublicDto dateOfVersion(OffsetDateTime dateOfVersion) {

    this.dateOfVersion = dateOfVersion;
    return this;
  }

  /**
   * Get dateOfVersion
   *
   * @return dateOfVersion
   */
  @jakarta.annotation.Nullable
  @Valid
  @JsonProperty(JSON_PROPERTY_DATE_OF_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getDateOfVersion() {
    return dateOfVersion;
  }

  @JsonProperty(JSON_PROPERTY_DATE_OF_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateOfVersion(OffsetDateTime dateOfVersion) {
    this.dateOfVersion = dateOfVersion;
  }

  public AIADomainSpecificModelPublicDto dateOfDeactivation(OffsetDateTime dateOfDeactivation) {

    this.dateOfDeactivation = dateOfDeactivation;
    return this;
  }

  /**
   * Get dateOfDeactivation
   *
   * @return dateOfDeactivation
   */
  @jakarta.annotation.Nullable
  @Valid
  @JsonProperty(JSON_PROPERTY_DATE_OF_DEACTIVATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getDateOfDeactivation() {
    return dateOfDeactivation;
  }

  @JsonProperty(JSON_PROPERTY_DATE_OF_DEACTIVATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateOfDeactivation(OffsetDateTime dateOfDeactivation) {
    this.dateOfDeactivation = dateOfDeactivation;
  }

  public AIADomainSpecificModelPublicDto guid(UUID guid) {

    this.guid = guid;
    return this;
  }

  /**
   * Get guid
   *
   * @return guid
   */
  @jakarta.annotation.Nullable
  @Valid
  @JsonProperty(JSON_PROPERTY_GUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getGuid() {
    return guid;
  }

  @JsonProperty(JSON_PROPERTY_GUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGuid(UUID guid) {
    this.guid = guid;
  }

  public AIADomainSpecificModelPublicDto name(String name) {

    this.name = name;
    return this;
  }

  /**
   * Get name
   *
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }

  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }

  public AIADomainSpecificModelPublicDto description(String description) {

    this.description = description;
    return this;
  }

  /**
   * Get description
   *
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }

  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }

  public AIADomainSpecificModelPublicDto organisationId(UUID organisationId) {

    this.organisationId = organisationId;
    return this;
  }

  /**
   * Get organisationId
   *
   * @return organisationId
   */
  @jakarta.annotation.Nullable
  @Valid
  @JsonProperty(JSON_PROPERTY_ORGANISATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getOrganisationId() {
    return organisationId;
  }

  @JsonProperty(JSON_PROPERTY_ORGANISATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrganisationId(UUID organisationId) {
    this.organisationId = organisationId;
  }

  public AIADomainSpecificModelPublicDto organisationName(String organisationName) {

    this.organisationName = organisationName;
    return this;
  }

  /**
   * Get organisationName
   *
   * @return organisationName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORGANISATION_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getOrganisationName() {
    return organisationName;
  }

  @JsonProperty(JSON_PROPERTY_ORGANISATION_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrganisationName(String organisationName) {
    this.organisationName = organisationName;
  }

  public AIADomainSpecificModelPublicDto versionNumber(Long versionNumber) {

    this.versionNumber = versionNumber;
    return this;
  }

  /**
   * Get versionNumber
   *
   * @return versionNumber
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERSION_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getVersionNumber() {
    return versionNumber;
  }

  @JsonProperty(JSON_PROPERTY_VERSION_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersionNumber(Long versionNumber) {
    this.versionNumber = versionNumber;
  }

  public AIADomainSpecificModelPublicDto revisionNumber(Long revisionNumber) {

    this.revisionNumber = revisionNumber;
    return this;
  }

  /**
   * Get revisionNumber
   *
   * @return revisionNumber
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REVISION_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getRevisionNumber() {
    return revisionNumber;
  }

  @JsonProperty(JSON_PROPERTY_REVISION_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRevisionNumber(Long revisionNumber) {
    this.revisionNumber = revisionNumber;
  }

  public AIADomainSpecificModelPublicDto buildNumber(Long buildNumber) {

    this.buildNumber = buildNumber;
    return this;
  }

  /**
   * Get buildNumber
   *
   * @return buildNumber
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BUILD_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getBuildNumber() {
    return buildNumber;
  }

  @JsonProperty(JSON_PROPERTY_BUILD_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBuildNumber(Long buildNumber) {
    this.buildNumber = buildNumber;
  }

  public AIADomainSpecificModelPublicDto exportFormats(Set<String> exportFormats) {

    this.exportFormats = exportFormats;
    return this;
  }

  public AIADomainSpecificModelPublicDto addExportFormatsItem(String exportFormatsItem) {
    if (this.exportFormats == null) {
      this.exportFormats = new LinkedHashSet<>();
    }
    this.exportFormats.add(exportFormatsItem);
    return this;
  }

  /**
   * Get exportFormats
   *
   * @return exportFormats
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPORT_FORMATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Set<String> getExportFormats() {
    return exportFormats;
  }

  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_EXPORT_FORMATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExportFormats(Set<String> exportFormats) {
    this.exportFormats = exportFormats;
  }

  public AIADomainSpecificModelPublicDto templateType(TemplateTypeEnum templateType) {

    this.templateType = templateType;
    return this;
  }

  /**
   * Get templateType
   *
   * @return templateType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEMPLATE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public TemplateTypeEnum getTemplateType() {
    return templateType;
  }

  @JsonProperty(JSON_PROPERTY_TEMPLATE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTemplateType(TemplateTypeEnum templateType) {
    this.templateType = templateType;
  }

  public AIADomainSpecificModelPublicDto chapters(List<@Valid ChapterPublicReference> chapters) {

    this.chapters = chapters;
    return this;
  }

  public AIADomainSpecificModelPublicDto addChaptersItem(ChapterPublicReference chaptersItem) {
    if (this.chapters == null) {
      this.chapters = new ArrayList<>();
    }
    this.chapters.add(chaptersItem);
    return this;
  }

  /**
   * Get chapters
   *
   * @return chapters
   */
  @jakarta.annotation.Nullable
  @Valid
  @JsonProperty(JSON_PROPERTY_CHAPTERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid ChapterPublicReference> getChapters() {
    return chapters;
  }

  @JsonProperty(JSON_PROPERTY_CHAPTERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChapters(List<@Valid ChapterPublicReference> chapters) {
    this.chapters = chapters;
  }

  public AIADomainSpecificModelPublicDto loins(List<@Valid LoinPublicReference> loins) {

    this.loins = loins;
    return this;
  }

  public AIADomainSpecificModelPublicDto addLoinsItem(LoinPublicReference loinsItem) {
    if (this.loins == null) {
      this.loins = new ArrayList<>();
    }
    this.loins.add(loinsItem);
    return this;
  }

  /**
   * Get loins
   *
   * @return loins
   */
  @jakarta.annotation.Nullable
  @Valid
  @JsonProperty(JSON_PROPERTY_LOINS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid LoinPublicReference> getLoins() {
    return loins;
  }

  @JsonProperty(JSON_PROPERTY_LOINS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoins(List<@Valid LoinPublicReference> loins) {
    this.loins = loins;
  }

  public AIADomainSpecificModelPublicDto dataFormats(
      Set<LOINPublicDtoDataFormatsInner> dataFormats) {

    this.dataFormats = dataFormats;
    return this;
  }

  public AIADomainSpecificModelPublicDto addDataFormatsItem(
      LOINPublicDtoDataFormatsInner dataFormatsItem) {
    if (this.dataFormats == null) {
      this.dataFormats = new LinkedHashSet<>();
    }
    this.dataFormats.add(dataFormatsItem);
    return this;
  }

  /**
   * Get dataFormats
   *
   * @return dataFormats
   */
  @jakarta.annotation.Nullable
  @Valid
  @JsonProperty(JSON_PROPERTY_DATA_FORMATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Set<LOINPublicDtoDataFormatsInner> getDataFormats() {
    return dataFormats;
  }

  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_DATA_FORMATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDataFormats(Set<LOINPublicDtoDataFormatsInner> dataFormats) {
    this.dataFormats = dataFormats;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AIADomainSpecificModelPublicDto aiADomainSpecificModelPublicDto =
        (AIADomainSpecificModelPublicDto) o;
    return Objects.equals(this.id, aiADomainSpecificModelPublicDto.id)
        && Objects.equals(this.createdDate, aiADomainSpecificModelPublicDto.createdDate)
        && Objects.equals(this.dateOfActivation, aiADomainSpecificModelPublicDto.dateOfActivation)
        && Objects.equals(this.dateOfLastChange, aiADomainSpecificModelPublicDto.dateOfLastChange)
        && Objects.equals(this.dateOfRevision, aiADomainSpecificModelPublicDto.dateOfRevision)
        && Objects.equals(this.dateOfVersion, aiADomainSpecificModelPublicDto.dateOfVersion)
        && Objects.equals(
            this.dateOfDeactivation, aiADomainSpecificModelPublicDto.dateOfDeactivation)
        && Objects.equals(this.guid, aiADomainSpecificModelPublicDto.guid)
        && Objects.equals(this.name, aiADomainSpecificModelPublicDto.name)
        && Objects.equals(this.description, aiADomainSpecificModelPublicDto.description)
        && Objects.equals(this.organisationId, aiADomainSpecificModelPublicDto.organisationId)
        && Objects.equals(this.organisationName, aiADomainSpecificModelPublicDto.organisationName)
        && Objects.equals(this.versionNumber, aiADomainSpecificModelPublicDto.versionNumber)
        && Objects.equals(this.revisionNumber, aiADomainSpecificModelPublicDto.revisionNumber)
        && Objects.equals(this.buildNumber, aiADomainSpecificModelPublicDto.buildNumber)
        && Objects.equals(this.exportFormats, aiADomainSpecificModelPublicDto.exportFormats)
        && Objects.equals(this.templateType, aiADomainSpecificModelPublicDto.templateType)
        && Objects.equals(this.chapters, aiADomainSpecificModelPublicDto.chapters)
        && Objects.equals(this.loins, aiADomainSpecificModelPublicDto.loins)
        && Objects.equals(this.dataFormats, aiADomainSpecificModelPublicDto.dataFormats);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        id,
        createdDate,
        dateOfActivation,
        dateOfLastChange,
        dateOfRevision,
        dateOfVersion,
        dateOfDeactivation,
        guid,
        name,
        description,
        organisationId,
        organisationName,
        versionNumber,
        revisionNumber,
        buildNumber,
        exportFormats,
        templateType,
        chapters,
        loins,
        dataFormats);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AIADomainSpecificModelPublicDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    dateOfActivation: ").append(toIndentedString(dateOfActivation)).append("\n");
    sb.append("    dateOfLastChange: ").append(toIndentedString(dateOfLastChange)).append("\n");
    sb.append("    dateOfRevision: ").append(toIndentedString(dateOfRevision)).append("\n");
    sb.append("    dateOfVersion: ").append(toIndentedString(dateOfVersion)).append("\n");
    sb.append("    dateOfDeactivation: ").append(toIndentedString(dateOfDeactivation)).append("\n");
    sb.append("    guid: ").append(toIndentedString(guid)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    organisationId: ").append(toIndentedString(organisationId)).append("\n");
    sb.append("    organisationName: ").append(toIndentedString(organisationName)).append("\n");
    sb.append("    versionNumber: ").append(toIndentedString(versionNumber)).append("\n");
    sb.append("    revisionNumber: ").append(toIndentedString(revisionNumber)).append("\n");
    sb.append("    buildNumber: ").append(toIndentedString(buildNumber)).append("\n");
    sb.append("    exportFormats: ").append(toIndentedString(exportFormats)).append("\n");
    sb.append("    templateType: ").append(toIndentedString(templateType)).append("\n");
    sb.append("    chapters: ").append(toIndentedString(chapters)).append("\n");
    sb.append("    loins: ").append(toIndentedString(loins)).append("\n");
    sb.append("    dataFormats: ").append(toIndentedString(dataFormats)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
