/*
 * BIM-Portal REST-API
 * Dies ist die Dokumentation der REST-Endpunkte, die sowohl öffentliche als auch private Informationselemente abrufen können. Authentifizierung ist für den Zugriff auf private Ressourcen erforderlich. Die Endpunkte können auf dieser Seite getestet werden.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.bimportal.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;
import org.hibernate.validator.constraints.*;

/** AiaProjectForPublicRequest */
@JsonPropertyOrder({
  AiaProjectForPublicRequest.JSON_PROPERTY_REFERENCED_IDS,
  AiaProjectForPublicRequest.JSON_PROPERTY_ORGANISATION_GUIDS,
  AiaProjectForPublicRequest.JSON_PROPERTY_SEARCH_STRING,
  AiaProjectForPublicRequest.JSON_PROPERTY_CONTEXT_IDS,
  AiaProjectForPublicRequest.JSON_PROPERTY_INCLUDE_DEPRECATED,
  AiaProjectForPublicRequest.JSON_PROPERTY_PAGE_NUMBER
})
@jakarta.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2025-09-03T22:05:51.794303+02:00[Europe/Berlin]",
    comments = "Generator version: 7.9.0")
public class AiaProjectForPublicRequest {
  public static final String JSON_PROPERTY_REFERENCED_IDS = "referencedIds";
  private List<UUID> referencedIds = new ArrayList<>();

  public static final String JSON_PROPERTY_ORGANISATION_GUIDS = "organisationGuids";
  private Set<UUID> organisationGuids = new LinkedHashSet<>();

  public static final String JSON_PROPERTY_SEARCH_STRING = "searchString";
  private String searchString;

  public static final String JSON_PROPERTY_CONTEXT_IDS = "contextIds";
  private List<UUID> contextIds = new ArrayList<>();

  public static final String JSON_PROPERTY_INCLUDE_DEPRECATED = "includeDeprecated";
  private Boolean includeDeprecated;

  public static final String JSON_PROPERTY_PAGE_NUMBER = "pageNumber";
  private Integer pageNumber;

  public AiaProjectForPublicRequest() {}

  public AiaProjectForPublicRequest referencedIds(List<UUID> referencedIds) {

    this.referencedIds = referencedIds;
    return this;
  }

  public AiaProjectForPublicRequest addReferencedIdsItem(UUID referencedIdsItem) {
    if (this.referencedIds == null) {
      this.referencedIds = new ArrayList<>();
    }
    this.referencedIds.add(referencedIdsItem);
    return this;
  }

  /**
   * GUIDs der Fachmodelle/Projektvorlagen, die die zu liefernden Projekte referenzieren müssen
   *
   * @return referencedIds
   */
  @jakarta.annotation.Nullable
  @Valid
  @JsonProperty(JSON_PROPERTY_REFERENCED_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<UUID> getReferencedIds() {
    return referencedIds;
  }

  @JsonProperty(JSON_PROPERTY_REFERENCED_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReferencedIds(List<UUID> referencedIds) {
    this.referencedIds = referencedIds;
  }

  public AiaProjectForPublicRequest organisationGuids(Set<UUID> organisationGuids) {

    this.organisationGuids = organisationGuids;
    return this;
  }

  public AiaProjectForPublicRequest addOrganisationGuidsItem(UUID organisationGuidsItem) {
    if (this.organisationGuids == null) {
      this.organisationGuids = new LinkedHashSet<>();
    }
    this.organisationGuids.add(organisationGuidsItem);
    return this;
  }

  /**
   * GUIDs der Organisationen, denen die Projekte angehören müssen
   *
   * @return organisationGuids
   */
  @jakarta.annotation.Nullable
  @Valid
  @JsonProperty(JSON_PROPERTY_ORGANISATION_GUIDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Set<UUID> getOrganisationGuids() {
    return organisationGuids;
  }

  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_ORGANISATION_GUIDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrganisationGuids(Set<UUID> organisationGuids) {
    this.organisationGuids = organisationGuids;
  }

  public AiaProjectForPublicRequest searchString(String searchString) {

    this.searchString = searchString;
    return this;
  }

  /**
   * Teilstring, den die Namen der zu liefernden Projekte beinhalten müssen
   *
   * @return searchString
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEARCH_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSearchString() {
    return searchString;
  }

  @JsonProperty(JSON_PROPERTY_SEARCH_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSearchString(String searchString) {
    this.searchString = searchString;
  }

  public AiaProjectForPublicRequest contextIds(List<UUID> contextIds) {

    this.contextIds = contextIds;
    return this;
  }

  public AiaProjectForPublicRequest addContextIdsItem(UUID contextIdsItem) {
    if (this.contextIds == null) {
      this.contextIds = new ArrayList<>();
    }
    this.contextIds.add(contextIdsItem);
    return this;
  }

  /**
   * GUIDs der Kontextinformationen, die die zu liefernden Projekte referenzieren müssen
   *
   * @return contextIds
   */
  @jakarta.annotation.Nullable
  @Valid
  @JsonProperty(JSON_PROPERTY_CONTEXT_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<UUID> getContextIds() {
    return contextIds;
  }

  @JsonProperty(JSON_PROPERTY_CONTEXT_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContextIds(List<UUID> contextIds) {
    this.contextIds = contextIds;
  }

  public AiaProjectForPublicRequest includeDeprecated(Boolean includeDeprecated) {

    this.includeDeprecated = includeDeprecated;
    return this;
  }

  /**
   * true, wenn auch veraltete Projekte mitgeliefert werden sollen
   *
   * @return includeDeprecated
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INCLUDE_DEPRECATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIncludeDeprecated() {
    return includeDeprecated;
  }

  @JsonProperty(JSON_PROPERTY_INCLUDE_DEPRECATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIncludeDeprecated(Boolean includeDeprecated) {
    this.includeDeprecated = includeDeprecated;
  }

  public AiaProjectForPublicRequest pageNumber(Integer pageNumber) {

    this.pageNumber = pageNumber;
    return this;
  }

  /**
   * Laufende Nummer der Ergebnisseite
   *
   * @return pageNumber
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAGE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getPageNumber() {
    return pageNumber;
  }

  @JsonProperty(JSON_PROPERTY_PAGE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPageNumber(Integer pageNumber) {
    this.pageNumber = pageNumber;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AiaProjectForPublicRequest aiaProjectForPublicRequest = (AiaProjectForPublicRequest) o;
    return Objects.equals(this.referencedIds, aiaProjectForPublicRequest.referencedIds)
        && Objects.equals(this.organisationGuids, aiaProjectForPublicRequest.organisationGuids)
        && Objects.equals(this.searchString, aiaProjectForPublicRequest.searchString)
        && Objects.equals(this.contextIds, aiaProjectForPublicRequest.contextIds)
        && Objects.equals(this.includeDeprecated, aiaProjectForPublicRequest.includeDeprecated)
        && Objects.equals(this.pageNumber, aiaProjectForPublicRequest.pageNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        referencedIds, organisationGuids, searchString, contextIds, includeDeprecated, pageNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AiaProjectForPublicRequest {\n");
    sb.append("    referencedIds: ").append(toIndentedString(referencedIds)).append("\n");
    sb.append("    organisationGuids: ").append(toIndentedString(organisationGuids)).append("\n");
    sb.append("    searchString: ").append(toIndentedString(searchString)).append("\n");
    sb.append("    contextIds: ").append(toIndentedString(contextIds)).append("\n");
    sb.append("    includeDeprecated: ").append(toIndentedString(includeDeprecated)).append("\n");
    sb.append("    pageNumber: ").append(toIndentedString(pageNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
