/*
 * BIM-Portal REST-API
 * Dies ist die Dokumentation der REST-Endpunkte, die sowohl öffentliche als auch private Informationselemente abrufen können. Authentifizierung ist für den Zugriff auf private Ressourcen erforderlich. Die Endpunkte können auf dieser Seite getestet werden.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.bimportal.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import org.hibernate.validator.constraints.*;

/** AutomaticDomainSpecificModelEntryPublicReference */
@JsonPropertyOrder({
  AutomaticDomainSpecificModelEntryPublicReference.JSON_PROPERTY_CONTEXTS,
  AutomaticDomainSpecificModelEntryPublicReference.JSON_PROPERTY_LOINS
})
@jakarta.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2025-09-03T22:05:51.794303+02:00[Europe/Berlin]",
    comments = "Generator version: 7.9.0")
public class AutomaticDomainSpecificModelEntryPublicReference {
  public static final String JSON_PROPERTY_CONTEXTS = "contexts";
  private List<@Valid ContextInfoPublicReference> contexts = new ArrayList<>();

  public static final String JSON_PROPERTY_LOINS = "loins";
  private List<@Valid LoinPublicReference> loins = new ArrayList<>();

  public AutomaticDomainSpecificModelEntryPublicReference() {}

  public AutomaticDomainSpecificModelEntryPublicReference contexts(
      List<@Valid ContextInfoPublicReference> contexts) {

    this.contexts = contexts;
    return this;
  }

  public AutomaticDomainSpecificModelEntryPublicReference addContextsItem(
      ContextInfoPublicReference contextsItem) {
    if (this.contexts == null) {
      this.contexts = new ArrayList<>();
    }
    this.contexts.add(contextsItem);
    return this;
  }

  /**
   * Get contexts
   *
   * @return contexts
   */
  @jakarta.annotation.Nullable
  @Valid
  @JsonProperty(JSON_PROPERTY_CONTEXTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid ContextInfoPublicReference> getContexts() {
    return contexts;
  }

  @JsonProperty(JSON_PROPERTY_CONTEXTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContexts(List<@Valid ContextInfoPublicReference> contexts) {
    this.contexts = contexts;
  }

  public AutomaticDomainSpecificModelEntryPublicReference loins(
      List<@Valid LoinPublicReference> loins) {

    this.loins = loins;
    return this;
  }

  public AutomaticDomainSpecificModelEntryPublicReference addLoinsItem(
      LoinPublicReference loinsItem) {
    if (this.loins == null) {
      this.loins = new ArrayList<>();
    }
    this.loins.add(loinsItem);
    return this;
  }

  /**
   * Get loins
   *
   * @return loins
   */
  @jakarta.annotation.Nullable
  @Valid
  @JsonProperty(JSON_PROPERTY_LOINS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid LoinPublicReference> getLoins() {
    return loins;
  }

  @JsonProperty(JSON_PROPERTY_LOINS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoins(List<@Valid LoinPublicReference> loins) {
    this.loins = loins;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AutomaticDomainSpecificModelEntryPublicReference
        automaticDomainSpecificModelEntryPublicReference =
            (AutomaticDomainSpecificModelEntryPublicReference) o;
    return Objects.equals(this.contexts, automaticDomainSpecificModelEntryPublicReference.contexts)
        && Objects.equals(this.loins, automaticDomainSpecificModelEntryPublicReference.loins);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contexts, loins);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AutomaticDomainSpecificModelEntryPublicReference {\n");
    sb.append("    contexts: ").append(toIndentedString(contexts)).append("\n");
    sb.append("    loins: ").append(toIndentedString(loins)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
