/*
 * BIM-Portal REST-API
 * Dies ist die Dokumentation der REST-Endpunkte, die sowohl öffentliche als auch private Informationselemente abrufen können. Authentifizierung ist für den Zugriff auf private Ressourcen erforderlich. Die Endpunkte können auf dieser Seite getestet werden.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.bimportal.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.math.BigDecimal;
import java.util.Objects;
import org.hibernate.validator.constraints.*;

/** CoordinateSystem */
@JsonPropertyOrder({
  CoordinateSystem.JSON_PROPERTY_NAME,
  CoordinateSystem.JSON_PROPERTY_ZONE,
  CoordinateSystem.JSON_PROPERTY_EAST,
  CoordinateSystem.JSON_PROPERTY_NORTH,
  CoordinateSystem.JSON_PROPERTY_HEIGHT
})
@jakarta.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2025-09-03T22:05:51.794303+02:00[Europe/Berlin]",
    comments = "Generator version: 7.9.0")
public class CoordinateSystem {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_ZONE = "zone";
  private String zone;

  public static final String JSON_PROPERTY_EAST = "east";
  private BigDecimal east;

  public static final String JSON_PROPERTY_NORTH = "north";
  private BigDecimal north;

  public static final String JSON_PROPERTY_HEIGHT = "height";
  private BigDecimal height;

  public CoordinateSystem() {}

  public CoordinateSystem name(String name) {

    this.name = name;
    return this;
  }

  /**
   * Get name
   *
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }

  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }

  public CoordinateSystem zone(String zone) {

    this.zone = zone;
    return this;
  }

  /**
   * Get zone
   *
   * @return zone
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ZONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getZone() {
    return zone;
  }

  @JsonProperty(JSON_PROPERTY_ZONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setZone(String zone) {
    this.zone = zone;
  }

  public CoordinateSystem east(BigDecimal east) {

    this.east = east;
    return this;
  }

  /**
   * Get east
   *
   * @return east
   */
  @jakarta.annotation.Nullable
  @Valid
  @JsonProperty(JSON_PROPERTY_EAST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getEast() {
    return east;
  }

  @JsonProperty(JSON_PROPERTY_EAST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEast(BigDecimal east) {
    this.east = east;
  }

  public CoordinateSystem north(BigDecimal north) {

    this.north = north;
    return this;
  }

  /**
   * Get north
   *
   * @return north
   */
  @jakarta.annotation.Nullable
  @Valid
  @JsonProperty(JSON_PROPERTY_NORTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getNorth() {
    return north;
  }

  @JsonProperty(JSON_PROPERTY_NORTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNorth(BigDecimal north) {
    this.north = north;
  }

  public CoordinateSystem height(BigDecimal height) {

    this.height = height;
    return this;
  }

  /**
   * Get height
   *
   * @return height
   */
  @jakarta.annotation.Nullable
  @Valid
  @JsonProperty(JSON_PROPERTY_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getHeight() {
    return height;
  }

  @JsonProperty(JSON_PROPERTY_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeight(BigDecimal height) {
    this.height = height;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CoordinateSystem coordinateSystem = (CoordinateSystem) o;
    return Objects.equals(this.name, coordinateSystem.name)
        && Objects.equals(this.zone, coordinateSystem.zone)
        && Objects.equals(this.east, coordinateSystem.east)
        && Objects.equals(this.north, coordinateSystem.north)
        && Objects.equals(this.height, coordinateSystem.height);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, zone, east, north, height);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CoordinateSystem {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    zone: ").append(toIndentedString(zone)).append("\n");
    sb.append("    east: ").append(toIndentedString(east)).append("\n");
    sb.append("    north: ").append(toIndentedString(north)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
