/*
 * BIM-Portal REST-API
 * Dies ist die Dokumentation der REST-Endpunkte, die sowohl öffentliche als auch private Informationselemente abrufen können. Authentifizierung ist für den Zugriff auf private Ressourcen erforderlich. Die Endpunkte können auf dieser Seite getestet werden.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.bimportal.client.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.Objects;
import java.util.UUID;
import org.hibernate.validator.constraints.*;

/** LOINPublicDtoDataFormatsInner */
@JsonPropertyOrder({
  LOINPublicDtoDataFormatsInner.JSON_PROPERTY_ID,
  LOINPublicDtoDataFormatsInner.JSON_PROPERTY_TYPE,
  LOINPublicDtoDataFormatsInner.JSON_PROPERTY_AT_CLASS,
  LOINPublicDtoDataFormatsInner.JSON_PROPERTY_FILE_ID,
  LOINPublicDtoDataFormatsInner.JSON_PROPERTY_FILE_NAME,
  LOINPublicDtoDataFormatsInner.JSON_PROPERTY_NAME,
  LOINPublicDtoDataFormatsInner.JSON_PROPERTY_DATA_FORMAT_VERSION,
  LOINPublicDtoDataFormatsInner.JSON_PROPERTY_VIEW_TYPE
})
@jakarta.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2025-09-03T22:05:51.794303+02:00[Europe/Berlin]",
    comments = "Generator version: 7.9.0")
@JsonIgnoreProperties(
    value = "@class", // ignore manually set @class, it will be automatically generated by Jackson
    // during serialization
    allowSetters = true // allows the @class to be set during deserialization
    )
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.PROPERTY,
    property = "@class",
    visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = IFCDto.class, name = "IFCDto"),
  @JsonSubTypes.Type(value = OKSTRADto.class, name = "OKSTRADto"),
  @JsonSubTypes.Type(value = OtherDto.class, name = "OtherDto"),
})
public class LOINPublicDtoDataFormatsInner {
  public static final String JSON_PROPERTY_ID = "id";
  private UUID id;

  public static final String JSON_PROPERTY_TYPE = "type";
  private DataFormatTypeDto type;

  public static final String JSON_PROPERTY_AT_CLASS = "@class";
  protected String atClass;

  public static final String JSON_PROPERTY_FILE_ID = "fileId";
  private UUID fileId;

  public static final String JSON_PROPERTY_FILE_NAME = "fileName";
  private String fileName;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_DATA_FORMAT_VERSION = "dataFormatVersion";
  private String dataFormatVersion;

  public static final String JSON_PROPERTY_VIEW_TYPE = "viewType";
  private String viewType;

  public LOINPublicDtoDataFormatsInner() {}

  public LOINPublicDtoDataFormatsInner id(UUID id) {

    this.id = id;
    return this;
  }

  /**
   * Get id
   *
   * @return id
   */
  @jakarta.annotation.Nullable
  @Valid
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getId() {
    return id;
  }

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(UUID id) {
    this.id = id;
  }

  public LOINPublicDtoDataFormatsInner type(DataFormatTypeDto type) {

    this.type = type;
    return this;
  }

  /**
   * Get type
   *
   * @return type
   */
  @jakarta.annotation.Nullable
  @Valid
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public DataFormatTypeDto getType() {
    return type;
  }

  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(DataFormatTypeDto type) {
    this.type = type;
  }

  public LOINPublicDtoDataFormatsInner atClass(String atClass) {

    this.atClass = atClass;
    return this;
  }

  /**
   * Get atClass
   *
   * @return atClass
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @JsonProperty(JSON_PROPERTY_AT_CLASS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAtClass() {
    return atClass;
  }

  @JsonProperty(JSON_PROPERTY_AT_CLASS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAtClass(String atClass) {
    this.atClass = atClass;
  }

  public LOINPublicDtoDataFormatsInner fileId(UUID fileId) {

    this.fileId = fileId;
    return this;
  }

  /**
   * Get fileId
   *
   * @return fileId
   */
  @jakarta.annotation.Nullable
  @Valid
  @JsonProperty(JSON_PROPERTY_FILE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getFileId() {
    return fileId;
  }

  @JsonProperty(JSON_PROPERTY_FILE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFileId(UUID fileId) {
    this.fileId = fileId;
  }

  public LOINPublicDtoDataFormatsInner fileName(String fileName) {

    this.fileName = fileName;
    return this;
  }

  /**
   * Get fileName
   *
   * @return fileName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFileName() {
    return fileName;
  }

  @JsonProperty(JSON_PROPERTY_FILE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFileName(String fileName) {
    this.fileName = fileName;
  }

  public LOINPublicDtoDataFormatsInner name(String name) {

    this.name = name;
    return this;
  }

  /**
   * Get name
   *
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }

  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }

  public LOINPublicDtoDataFormatsInner dataFormatVersion(String dataFormatVersion) {

    this.dataFormatVersion = dataFormatVersion;
    return this;
  }

  /**
   * Get dataFormatVersion
   *
   * @return dataFormatVersion
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATA_FORMAT_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDataFormatVersion() {
    return dataFormatVersion;
  }

  @JsonProperty(JSON_PROPERTY_DATA_FORMAT_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDataFormatVersion(String dataFormatVersion) {
    this.dataFormatVersion = dataFormatVersion;
  }

  public LOINPublicDtoDataFormatsInner viewType(String viewType) {

    this.viewType = viewType;
    return this;
  }

  /**
   * Get viewType
   *
   * @return viewType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VIEW_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getViewType() {
    return viewType;
  }

  @JsonProperty(JSON_PROPERTY_VIEW_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setViewType(String viewType) {
    this.viewType = viewType;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LOINPublicDtoDataFormatsInner loINPublicDtoDataFormatsInner = (LOINPublicDtoDataFormatsInner) o;
    return Objects.equals(this.id, loINPublicDtoDataFormatsInner.id)
        && Objects.equals(this.type, loINPublicDtoDataFormatsInner.type)
        && Objects.equals(this.atClass, loINPublicDtoDataFormatsInner.atClass)
        && Objects.equals(this.fileId, loINPublicDtoDataFormatsInner.fileId)
        && Objects.equals(this.fileName, loINPublicDtoDataFormatsInner.fileName)
        && Objects.equals(this.name, loINPublicDtoDataFormatsInner.name)
        && Objects.equals(this.dataFormatVersion, loINPublicDtoDataFormatsInner.dataFormatVersion)
        && Objects.equals(this.viewType, loINPublicDtoDataFormatsInner.viewType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, atClass, fileId, fileName, name, dataFormatVersion, viewType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LOINPublicDtoDataFormatsInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    atClass: ").append(toIndentedString(atClass)).append("\n");
    sb.append("    fileId: ").append(toIndentedString(fileId)).append("\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    dataFormatVersion: ").append(toIndentedString(dataFormatVersion)).append("\n");
    sb.append("    viewType: ").append(toIndentedString(viewType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
