/*
 * BIM-Portal REST-API
 * Dies ist die Dokumentation der REST-Endpunkte, die sowohl öffentliche als auch private Informationselemente abrufen können. Authentifizierung ist für den Zugriff auf private Ressourcen erforderlich. Die Endpunkte können auf dieser Seite getestet werden.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.bimportal.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.Objects;
import java.util.UUID;
import org.hibernate.validator.constraints.*;

/** OrganisationForPublicDTO */
@JsonPropertyOrder({
  OrganisationForPublicDTO.JSON_PROPERTY_NAME,
  OrganisationForPublicDTO.JSON_PROPERTY_DESCRIPTION,
  OrganisationForPublicDTO.JSON_PROPERTY_GUID,
  OrganisationForPublicDTO.JSON_PROPERTY_PARENT_GUID,
  OrganisationForPublicDTO.JSON_PROPERTY_BUND_ORGANISATION_OR_CHILD
})
@jakarta.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2025-09-03T22:05:51.794303+02:00[Europe/Berlin]",
    comments = "Generator version: 7.9.0")
public class OrganisationForPublicDTO {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_GUID = "guid";
  private UUID guid;

  public static final String JSON_PROPERTY_PARENT_GUID = "parentGuid";
  private UUID parentGuid;

  public static final String JSON_PROPERTY_BUND_ORGANISATION_OR_CHILD = "bundOrganisationOrChild";
  private Boolean bundOrganisationOrChild;

  public OrganisationForPublicDTO() {}

  public OrganisationForPublicDTO name(String name) {

    this.name = name;
    return this;
  }

  /**
   * Get name
   *
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }

  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }

  public OrganisationForPublicDTO description(String description) {

    this.description = description;
    return this;
  }

  /**
   * Get description
   *
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }

  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }

  public OrganisationForPublicDTO guid(UUID guid) {

    this.guid = guid;
    return this;
  }

  /**
   * Get guid
   *
   * @return guid
   */
  @jakarta.annotation.Nullable
  @Valid
  @JsonProperty(JSON_PROPERTY_GUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getGuid() {
    return guid;
  }

  @JsonProperty(JSON_PROPERTY_GUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGuid(UUID guid) {
    this.guid = guid;
  }

  public OrganisationForPublicDTO parentGuid(UUID parentGuid) {

    this.parentGuid = parentGuid;
    return this;
  }

  /**
   * Get parentGuid
   *
   * @return parentGuid
   */
  @jakarta.annotation.Nullable
  @Valid
  @JsonProperty(JSON_PROPERTY_PARENT_GUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getParentGuid() {
    return parentGuid;
  }

  @JsonProperty(JSON_PROPERTY_PARENT_GUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParentGuid(UUID parentGuid) {
    this.parentGuid = parentGuid;
  }

  public OrganisationForPublicDTO bundOrganisationOrChild(Boolean bundOrganisationOrChild) {

    this.bundOrganisationOrChild = bundOrganisationOrChild;
    return this;
  }

  /**
   * Get bundOrganisationOrChild
   *
   * @return bundOrganisationOrChild
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BUND_ORGANISATION_OR_CHILD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getBundOrganisationOrChild() {
    return bundOrganisationOrChild;
  }

  @JsonProperty(JSON_PROPERTY_BUND_ORGANISATION_OR_CHILD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBundOrganisationOrChild(Boolean bundOrganisationOrChild) {
    this.bundOrganisationOrChild = bundOrganisationOrChild;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganisationForPublicDTO organisationForPublicDTO = (OrganisationForPublicDTO) o;
    return Objects.equals(this.name, organisationForPublicDTO.name)
        && Objects.equals(this.description, organisationForPublicDTO.description)
        && Objects.equals(this.guid, organisationForPublicDTO.guid)
        && Objects.equals(this.parentGuid, organisationForPublicDTO.parentGuid)
        && Objects.equals(
            this.bundOrganisationOrChild, organisationForPublicDTO.bundOrganisationOrChild);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, guid, parentGuid, bundOrganisationOrChild);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganisationForPublicDTO {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    guid: ").append(toIndentedString(guid)).append("\n");
    sb.append("    parentGuid: ").append(toIndentedString(parentGuid)).append("\n");
    sb.append("    bundOrganisationOrChild: ")
        .append(toIndentedString(bundOrganisationOrChild))
        .append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
