/*
 * BIM-Portal REST-API
 * Dies ist die Dokumentation der REST-Endpunkte, die sowohl öffentliche als auch private Informationselemente abrufen können. Authentifizierung ist für den Zugriff auf private Ressourcen erforderlich. Die Endpunkte können auf dieser Seite getestet werden.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.bimportal.client.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;
import org.hibernate.validator.constraints.*;

/** SimpleParentGroup */
@JsonPropertyOrder({
  SimpleParentGroup.JSON_PROPERTY_ID,
  SimpleParentGroup.JSON_PROPERTY_NAMES_IN_LANGUAGE,
  SimpleParentGroup.JSON_PROPERTY_DEFINITIONS_IN_LANGUAGE,
  SimpleParentGroup.JSON_PROPERTY_VERSION_NUMBER,
  SimpleParentGroup.JSON_PROPERTY_REVISION_NUMBER,
  SimpleParentGroup.JSON_PROPERTY_INFORMATION_ELEMENT_STATUS,
  SimpleParentGroup.JSON_PROPERTY_CONTAINS_PROPERTY,
  SimpleParentGroup.JSON_PROPERTY_GUID,
  SimpleParentGroup.JSON_PROPERTY_CATEGORY_OF_GROUP_OF_PROPERTIES,
  SimpleParentGroup.JSON_PROPERTY_USER_CAN_VIEW_DETAILS,
  SimpleParentGroup.JSON_PROPERTY_VERSION_REVISION_STRING
})
@jakarta.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2025-09-03T22:05:51.794303+02:00[Europe/Berlin]",
    comments = "Generator version: 7.9.0")
public class SimpleParentGroup {
  public static final String JSON_PROPERTY_ID = "id";
  private UUID id;

  public static final String JSON_PROPERTY_NAMES_IN_LANGUAGE = "namesInLanguage";
  private List<@Valid NamesInLanguageDto> namesInLanguage = new ArrayList<>();

  public static final String JSON_PROPERTY_DEFINITIONS_IN_LANGUAGE = "definitionsInLanguage";
  private List<@Valid DefinitionsInLanguageDto> definitionsInLanguage = new ArrayList<>();

  public static final String JSON_PROPERTY_VERSION_NUMBER = "versionNumber";
  private Long versionNumber;

  public static final String JSON_PROPERTY_REVISION_NUMBER = "revisionNumber";
  private Long revisionNumber;

  /** Gets or Sets informationElementStatus */
  public enum InformationElementStatusEnum {
    INITIAL("INITIAL"),

    PROPOSED("PROPOSED"),

    CREATION("CREATION"),

    REVIEW("REVIEW"),

    VALIDATION("VALIDATION"),

    ACCEPTED("ACCEPTED"),

    PUBLISHED("PUBLISHED"),

    DEPRECATED("DEPRECATED"),

    SORTED_OUT("SORTED_OUT"),

    REJECTED("REJECTED");

    private String value;

    InformationElementStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static InformationElementStatusEnum fromValue(String value) {
      for (InformationElementStatusEnum b : InformationElementStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_INFORMATION_ELEMENT_STATUS = "informationElementStatus";
  private InformationElementStatusEnum informationElementStatus;

  public static final String JSON_PROPERTY_CONTAINS_PROPERTY = "containsProperty";
  private Boolean containsProperty;

  public static final String JSON_PROPERTY_GUID = "guid";
  private UUID guid;

  public static final String JSON_PROPERTY_CATEGORY_OF_GROUP_OF_PROPERTIES =
      "categoryOfGroupOfProperties";
  private String categoryOfGroupOfProperties;

  public static final String JSON_PROPERTY_USER_CAN_VIEW_DETAILS = "userCanViewDetails";
  private Boolean userCanViewDetails;

  public static final String JSON_PROPERTY_VERSION_REVISION_STRING = "versionRevisionString";
  private String versionRevisionString;

  public SimpleParentGroup() {}

  public SimpleParentGroup id(UUID id) {

    this.id = id;
    return this;
  }

  /**
   * Get id
   *
   * @return id
   */
  @jakarta.annotation.Nullable
  @Valid
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getId() {
    return id;
  }

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(UUID id) {
    this.id = id;
  }

  public SimpleParentGroup namesInLanguage(List<@Valid NamesInLanguageDto> namesInLanguage) {

    this.namesInLanguage = namesInLanguage;
    return this;
  }

  public SimpleParentGroup addNamesInLanguageItem(NamesInLanguageDto namesInLanguageItem) {
    if (this.namesInLanguage == null) {
      this.namesInLanguage = new ArrayList<>();
    }
    this.namesInLanguage.add(namesInLanguageItem);
    return this;
  }

  /**
   * Get namesInLanguage
   *
   * @return namesInLanguage
   */
  @jakarta.annotation.Nullable
  @Valid
  @JsonProperty(JSON_PROPERTY_NAMES_IN_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid NamesInLanguageDto> getNamesInLanguage() {
    return namesInLanguage;
  }

  @JsonProperty(JSON_PROPERTY_NAMES_IN_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNamesInLanguage(List<@Valid NamesInLanguageDto> namesInLanguage) {
    this.namesInLanguage = namesInLanguage;
  }

  public SimpleParentGroup definitionsInLanguage(
      List<@Valid DefinitionsInLanguageDto> definitionsInLanguage) {

    this.definitionsInLanguage = definitionsInLanguage;
    return this;
  }

  public SimpleParentGroup addDefinitionsInLanguageItem(
      DefinitionsInLanguageDto definitionsInLanguageItem) {
    if (this.definitionsInLanguage == null) {
      this.definitionsInLanguage = new ArrayList<>();
    }
    this.definitionsInLanguage.add(definitionsInLanguageItem);
    return this;
  }

  /**
   * Get definitionsInLanguage
   *
   * @return definitionsInLanguage
   */
  @jakarta.annotation.Nullable
  @Valid
  @JsonProperty(JSON_PROPERTY_DEFINITIONS_IN_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid DefinitionsInLanguageDto> getDefinitionsInLanguage() {
    return definitionsInLanguage;
  }

  @JsonProperty(JSON_PROPERTY_DEFINITIONS_IN_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefinitionsInLanguage(
      List<@Valid DefinitionsInLanguageDto> definitionsInLanguage) {
    this.definitionsInLanguage = definitionsInLanguage;
  }

  public SimpleParentGroup versionNumber(Long versionNumber) {

    this.versionNumber = versionNumber;
    return this;
  }

  /**
   * Get versionNumber
   *
   * @return versionNumber
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERSION_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getVersionNumber() {
    return versionNumber;
  }

  @JsonProperty(JSON_PROPERTY_VERSION_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersionNumber(Long versionNumber) {
    this.versionNumber = versionNumber;
  }

  public SimpleParentGroup revisionNumber(Long revisionNumber) {

    this.revisionNumber = revisionNumber;
    return this;
  }

  /**
   * Get revisionNumber
   *
   * @return revisionNumber
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REVISION_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getRevisionNumber() {
    return revisionNumber;
  }

  @JsonProperty(JSON_PROPERTY_REVISION_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRevisionNumber(Long revisionNumber) {
    this.revisionNumber = revisionNumber;
  }

  public SimpleParentGroup informationElementStatus(
      InformationElementStatusEnum informationElementStatus) {

    this.informationElementStatus = informationElementStatus;
    return this;
  }

  /**
   * Get informationElementStatus
   *
   * @return informationElementStatus
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INFORMATION_ELEMENT_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public InformationElementStatusEnum getInformationElementStatus() {
    return informationElementStatus;
  }

  @JsonProperty(JSON_PROPERTY_INFORMATION_ELEMENT_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInformationElementStatus(InformationElementStatusEnum informationElementStatus) {
    this.informationElementStatus = informationElementStatus;
  }

  public SimpleParentGroup containsProperty(Boolean containsProperty) {

    this.containsProperty = containsProperty;
    return this;
  }

  /**
   * Get containsProperty
   *
   * @return containsProperty
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTAINS_PROPERTY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getContainsProperty() {
    return containsProperty;
  }

  @JsonProperty(JSON_PROPERTY_CONTAINS_PROPERTY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContainsProperty(Boolean containsProperty) {
    this.containsProperty = containsProperty;
  }

  public SimpleParentGroup guid(UUID guid) {

    this.guid = guid;
    return this;
  }

  /**
   * Get guid
   *
   * @return guid
   */
  @jakarta.annotation.Nullable
  @Valid
  @JsonProperty(JSON_PROPERTY_GUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getGuid() {
    return guid;
  }

  @JsonProperty(JSON_PROPERTY_GUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGuid(UUID guid) {
    this.guid = guid;
  }

  public SimpleParentGroup categoryOfGroupOfProperties(String categoryOfGroupOfProperties) {

    this.categoryOfGroupOfProperties = categoryOfGroupOfProperties;
    return this;
  }

  /**
   * Get categoryOfGroupOfProperties
   *
   * @return categoryOfGroupOfProperties
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CATEGORY_OF_GROUP_OF_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCategoryOfGroupOfProperties() {
    return categoryOfGroupOfProperties;
  }

  @JsonProperty(JSON_PROPERTY_CATEGORY_OF_GROUP_OF_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCategoryOfGroupOfProperties(String categoryOfGroupOfProperties) {
    this.categoryOfGroupOfProperties = categoryOfGroupOfProperties;
  }

  public SimpleParentGroup userCanViewDetails(Boolean userCanViewDetails) {

    this.userCanViewDetails = userCanViewDetails;
    return this;
  }

  /**
   * Get userCanViewDetails
   *
   * @return userCanViewDetails
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_CAN_VIEW_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getUserCanViewDetails() {
    return userCanViewDetails;
  }

  @JsonProperty(JSON_PROPERTY_USER_CAN_VIEW_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserCanViewDetails(Boolean userCanViewDetails) {
    this.userCanViewDetails = userCanViewDetails;
  }

  public SimpleParentGroup versionRevisionString(String versionRevisionString) {

    this.versionRevisionString = versionRevisionString;
    return this;
  }

  /**
   * Get versionRevisionString
   *
   * @return versionRevisionString
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERSION_REVISION_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getVersionRevisionString() {
    return versionRevisionString;
  }

  @JsonProperty(JSON_PROPERTY_VERSION_REVISION_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersionRevisionString(String versionRevisionString) {
    this.versionRevisionString = versionRevisionString;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SimpleParentGroup simpleParentGroup = (SimpleParentGroup) o;
    return Objects.equals(this.id, simpleParentGroup.id)
        && Objects.equals(this.namesInLanguage, simpleParentGroup.namesInLanguage)
        && Objects.equals(this.definitionsInLanguage, simpleParentGroup.definitionsInLanguage)
        && Objects.equals(this.versionNumber, simpleParentGroup.versionNumber)
        && Objects.equals(this.revisionNumber, simpleParentGroup.revisionNumber)
        && Objects.equals(this.informationElementStatus, simpleParentGroup.informationElementStatus)
        && Objects.equals(this.containsProperty, simpleParentGroup.containsProperty)
        && Objects.equals(this.guid, simpleParentGroup.guid)
        && Objects.equals(
            this.categoryOfGroupOfProperties, simpleParentGroup.categoryOfGroupOfProperties)
        && Objects.equals(this.userCanViewDetails, simpleParentGroup.userCanViewDetails)
        && Objects.equals(this.versionRevisionString, simpleParentGroup.versionRevisionString);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        id,
        namesInLanguage,
        definitionsInLanguage,
        versionNumber,
        revisionNumber,
        informationElementStatus,
        containsProperty,
        guid,
        categoryOfGroupOfProperties,
        userCanViewDetails,
        versionRevisionString);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SimpleParentGroup {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    namesInLanguage: ").append(toIndentedString(namesInLanguage)).append("\n");
    sb.append("    definitionsInLanguage: ")
        .append(toIndentedString(definitionsInLanguage))
        .append("\n");
    sb.append("    versionNumber: ").append(toIndentedString(versionNumber)).append("\n");
    sb.append("    revisionNumber: ").append(toIndentedString(revisionNumber)).append("\n");
    sb.append("    informationElementStatus: ")
        .append(toIndentedString(informationElementStatus))
        .append("\n");
    sb.append("    containsProperty: ").append(toIndentedString(containsProperty)).append("\n");
    sb.append("    guid: ").append(toIndentedString(guid)).append("\n");
    sb.append("    categoryOfGroupOfProperties: ")
        .append(toIndentedString(categoryOfGroupOfProperties))
        .append("\n");
    sb.append("    userCanViewDetails: ").append(toIndentedString(userCanViewDetails)).append("\n");
    sb.append("    versionRevisionString: ")
        .append(toIndentedString(versionRevisionString))
        .append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
