/*
 * BIM-Portal REST-API
 * Dies ist die Dokumentation der REST-Endpunkte, die sowohl öffentliche als auch private Informationselemente abrufen können. Authentifizierung ist für den Zugriff auf private Ressourcen erforderlich. Die Endpunkte können auf dieser Seite getestet werden.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.bimportal.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.Objects;
import java.util.UUID;
import org.hibernate.validator.constraints.*;

/** TagDto */
@JsonPropertyOrder({
  TagDto.JSON_PROPERTY_ID,
  TagDto.JSON_PROPERTY_NAME,
  TagDto.JSON_PROPERTY_ORGANISATION_ID,
  TagDto.JSON_PROPERTY_GLOBAL,
  TagDto.JSON_PROPERTY_ASSIGNMENT_COUNT,
  TagDto.JSON_PROPERTY_GUID_REFERENCE
})
@jakarta.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    date = "2025-09-03T22:05:51.794303+02:00[Europe/Berlin]",
    comments = "Generator version: 7.9.0")
public class TagDto {
  public static final String JSON_PROPERTY_ID = "id";
  private UUID id;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_ORGANISATION_ID = "organisationId";
  private UUID organisationId;

  public static final String JSON_PROPERTY_GLOBAL = "global";
  private Boolean global;

  public static final String JSON_PROPERTY_ASSIGNMENT_COUNT = "assignmentCount";
  private Integer assignmentCount;

  public static final String JSON_PROPERTY_GUID_REFERENCE = "guidReference";
  private UUID guidReference;

  public TagDto() {}

  public TagDto id(UUID id) {

    this.id = id;
    return this;
  }

  /**
   * Get id
   *
   * @return id
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getId() {
    return id;
  }

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(UUID id) {
    this.id = id;
  }

  public TagDto name(String name) {

    this.name = name;
    return this;
  }

  /**
   * Get name
   *
   * @return name
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Size(min = 1)
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }

  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }

  public TagDto organisationId(UUID organisationId) {

    this.organisationId = organisationId;
    return this;
  }

  /**
   * Get organisationId
   *
   * @return organisationId
   */
  @jakarta.annotation.Nonnull
  @NotNull
  @Valid
  @JsonProperty(JSON_PROPERTY_ORGANISATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getOrganisationId() {
    return organisationId;
  }

  @JsonProperty(JSON_PROPERTY_ORGANISATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOrganisationId(UUID organisationId) {
    this.organisationId = organisationId;
  }

  public TagDto global(Boolean global) {

    this.global = global;
    return this;
  }

  /**
   * Get global
   *
   * @return global
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GLOBAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getGlobal() {
    return global;
  }

  @JsonProperty(JSON_PROPERTY_GLOBAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGlobal(Boolean global) {
    this.global = global;
  }

  public TagDto assignmentCount(Integer assignmentCount) {

    this.assignmentCount = assignmentCount;
    return this;
  }

  /**
   * Get assignmentCount
   *
   * @return assignmentCount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ASSIGNMENT_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getAssignmentCount() {
    return assignmentCount;
  }

  @JsonProperty(JSON_PROPERTY_ASSIGNMENT_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAssignmentCount(Integer assignmentCount) {
    this.assignmentCount = assignmentCount;
  }

  public TagDto guidReference(UUID guidReference) {

    this.guidReference = guidReference;
    return this;
  }

  /**
   * Get guidReference
   *
   * @return guidReference
   */
  @jakarta.annotation.Nullable
  @Valid
  @JsonProperty(JSON_PROPERTY_GUID_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getGuidReference() {
    return guidReference;
  }

  @JsonProperty(JSON_PROPERTY_GUID_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGuidReference(UUID guidReference) {
    this.guidReference = guidReference;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TagDto tagDto = (TagDto) o;
    return Objects.equals(this.id, tagDto.id)
        && Objects.equals(this.name, tagDto.name)
        && Objects.equals(this.organisationId, tagDto.organisationId)
        && Objects.equals(this.global, tagDto.global)
        && Objects.equals(this.assignmentCount, tagDto.assignmentCount)
        && Objects.equals(this.guidReference, tagDto.guidReference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, organisationId, global, assignmentCount, guidReference);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TagDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    organisationId: ").append(toIndentedString(organisationId)).append("\n");
    sb.append("    global: ").append(toIndentedString(global)).append("\n");
    sb.append("    assignmentCount: ").append(toIndentedString(assignmentCount)).append("\n");
    sb.append("    guidReference: ").append(toIndentedString(guidReference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
