/*
 * BIM-Portal REST-API
 * Dies ist die Dokumentation der REST-Endpunkte, die sowohl öffentliche als auch private Informationselemente abrufen können. Authentifizierung ist für den Zugriff auf private Ressourcen erforderlich. Die Endpunkte können auf dieser Seite getestet werden.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.bimportal.client.model;

import org.junit.jupiter.api.Test;

/** Model tests for AiaProjectForPublicRequest */
class AiaProjectForPublicRequestTest {
  private final AiaProjectForPublicRequest model = new AiaProjectForPublicRequest();

  /** Model tests for AiaProjectForPublicRequest */
  @Test
  void testAiaProjectForPublicRequest() {
    // TODO: test AiaProjectForPublicRequest
  }

  /** Test the property 'referencedIds' */
  @Test
  void referencedIdsTest() {
    // TODO: test referencedIds
  }

  /** Test the property 'organisationGuids' */
  @Test
  void organisationGuidsTest() {
    // TODO: test organisationGuids
  }

  /** Test the property 'searchString' */
  @Test
  void searchStringTest() {
    // TODO: test searchString
  }

  /** Test the property 'contextIds' */
  @Test
  void contextIdsTest() {
    // TODO: test contextIds
  }

  /** Test the property 'includeDeprecated' */
  @Test
  void includeDeprecatedTest() {
    // TODO: test includeDeprecated
  }

  /** Test the property 'pageNumber' */
  @Test
  void pageNumberTest() {
    // TODO: test pageNumber
  }
}
