/*
 * BIM-Portal REST-API
 * Dies ist die Dokumentation der REST-Endpunkte, die sowohl öffentliche als auch private Informationselemente abrufen können. Authentifizierung ist für den Zugriff auf private Ressourcen erforderlich. Die Endpunkte können auf dieser Seite getestet werden.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bimportal.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.UUID;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AiaTemplateForPublicRequest
 */
class AiaTemplateForPublicRequestTest {
    private final AiaTemplateForPublicRequest model = new AiaTemplateForPublicRequest();

    /**
     * Model tests for AiaTemplateForPublicRequest
     */
    @Test
    void testAiaTemplateForPublicRequest() {
        // TODO: test AiaTemplateForPublicRequest
    }

    /**
     * Test the property 'organisationGuids'
     */
    @Test
    void organisationGuidsTest() {
        // TODO: test organisationGuids
    }

    /**
     * Test the property 'searchString'
     */
    @Test
    void searchStringTest() {
        // TODO: test searchString
    }

    /**
     * Test the property 'contextIds'
     */
    @Test
    void contextIdsTest() {
        // TODO: test contextIds
    }

    /**
     * Test the property 'projectTemplate'
     */
    @Test
    void projectTemplateTest() {
        // TODO: test projectTemplate
    }

    /**
     * Test the property 'template'
     */
    @Test
    void templateTest() {
        // TODO: test template
    }

    /**
     * Test the property 'includeDeprecated'
     */
    @Test
    void includeDeprecatedTest() {
        // TODO: test includeDeprecated
    }

    /**
     * Test the property 'pageNumber'
     */
    @Test
    void pageNumberTest() {
        // TODO: test pageNumber
    }

}
