/*
 * BIM-Portal REST-API
 * Dies ist die Dokumentation der REST-Endpunkte, die sowohl öffentliche als auch private Informationselemente abrufen können. Authentifizierung ist für den Zugriff auf private Ressourcen erforderlich. Die Endpunkte können auf dieser Seite getestet werden.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bimportal.client.model;

import com.bimportal.client.model.ContextInfoPublicReference;
import com.bimportal.client.model.LoinPublicReference;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AutomaticDomainSpecificModelEntryPublicReference
 */
class AutomaticDomainSpecificModelEntryPublicReferenceTest {
    private final AutomaticDomainSpecificModelEntryPublicReference model = new AutomaticDomainSpecificModelEntryPublicReference();

    /**
     * Model tests for AutomaticDomainSpecificModelEntryPublicReference
     */
    @Test
    void testAutomaticDomainSpecificModelEntryPublicReference() {
        // TODO: test AutomaticDomainSpecificModelEntryPublicReference
    }

    /**
     * Test the property 'contexts'
     */
    @Test
    void contextsTest() {
        // TODO: test contexts
    }

    /**
     * Test the property 'loins'
     */
    @Test
    void loinsTest() {
        // TODO: test loins
    }

}
