/*
 * BIM-Portal REST-API
 * Dies ist die Dokumentation der REST-Endpunkte, die sowohl öffentliche als auch private Informationselemente abrufen können. Authentifizierung ist für den Zugriff auf private Ressourcen erforderlich. Die Endpunkte können auf dieser Seite getestet werden.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.bimportal.client.model;

import org.junit.jupiter.api.Test;

/** Model tests for ChapterPublicReference */
class ChapterPublicReferenceTest {
  private final ChapterPublicReference model = new ChapterPublicReference();

  /** Model tests for ChapterPublicReference */
  @Test
  void testChapterPublicReference() {
    // TODO: test ChapterPublicReference
  }

  /** Test the property 'title' */
  @Test
  void titleTest() {
    // TODO: test title
  }

  /** Test the property 'content' */
  @Test
  void contentTest() {
    // TODO: test content
  }

  /** Test the property 'chapterNumber' */
  @Test
  void chapterNumberTest() {
    // TODO: test chapterNumber
  }

  /** Test the property 'pleaseChange' */
  @Test
  void pleaseChangeTest() {
    // TODO: test pleaseChange
  }
}
