/*
 * BIM-Portal REST-API
 * Dies ist die Dokumentation der REST-Endpunkte, die sowohl öffentliche als auch private Informationselemente abrufen können. Authentifizierung ist für den Zugriff auf private Ressourcen erforderlich. Die Endpunkte können auf dieser Seite getestet werden.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.bimportal.client.model;

import org.junit.jupiter.api.Test;

/** Model tests for DataFormatType */
class DataFormatTypeTest {
  private final DataFormatType model = new DataFormatType();

  /** Model tests for DataFormatType */
  @Test
  void testDataFormatType() {
    // TODO: test DataFormatType
  }

  /** Test the property 'id' */
  @Test
  void idTest() {
    // TODO: test id
  }

  /** Test the property 'version' */
  @Test
  void versionTest() {
    // TODO: test version
  }

  /** Test the property 'createdDate' */
  @Test
  void createdDateTest() {
    // TODO: test createdDate
  }

  /** Test the property 'name' */
  @Test
  void nameTest() {
    // TODO: test name
  }

  /** Test the property 'majorRelease' */
  @Test
  void majorReleaseTest() {
    // TODO: test majorRelease
  }

  /** Test the property 'minorRelease' */
  @Test
  void minorReleaseTest() {
    // TODO: test minorRelease
  }

  /** Test the property 'addendum' */
  @Test
  void addendumTest() {
    // TODO: test addendum
  }

  /** Test the property 'corrigendum' */
  @Test
  void corrigendumTest() {
    // TODO: test corrigendum
  }

  /** Test the property 'variant' */
  @Test
  void variantTest() {
    // TODO: test variant
  }

  /** Test the property 'ifc' */
  @Test
  void ifcTest() {
    // TODO: test ifc
  }
}
