/*
 * BIM-Portal REST-API
 * Dies ist die Dokumentation der REST-Endpunkte, die sowohl öffentliche als auch private Informationselemente abrufen können. Authentifizierung ist für den Zugriff auf private Ressourcen erforderlich. Die Endpunkte können auf dieser Seite getestet werden.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.bimportal.client.model;

import org.junit.jupiter.api.Test;

/** Model tests for DefinitionsInLanguageDto */
class DefinitionsInLanguageDtoTest {
  private final DefinitionsInLanguageDto model = new DefinitionsInLanguageDto();

  /** Model tests for DefinitionsInLanguageDto */
  @Test
  void testDefinitionsInLanguageDto() {
    // TODO: test DefinitionsInLanguageDto
  }

  /** Test the property 'definition' */
  @Test
  void definitionTest() {
    // TODO: test definition
  }

  /** Test the property 'language' */
  @Test
  void languageTest() {
    // TODO: test language
  }

  /** Test the property 'value' */
  @Test
  void valueTest() {
    // TODO: test value
  }
}
