/*
 * BIM-Portal REST-API
 * Dies ist die Dokumentation der REST-Endpunkte, die sowohl öffentliche als auch private Informationselemente abrufen können. Authentifizierung ist für den Zugriff auf private Ressourcen erforderlich. Die Endpunkte können auf dieser Seite getestet werden.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.bimportal.client.model;

import org.junit.jupiter.api.Test;

/** Model tests for ExamplesInLanguageDto */
class ExamplesInLanguageDtoTest {
  private final ExamplesInLanguageDto model = new ExamplesInLanguageDto();

  /** Model tests for ExamplesInLanguageDto */
  @Test
  void testExamplesInLanguageDto() {
    // TODO: test ExamplesInLanguageDto
  }

  /** Test the property 'example' */
  @Test
  void exampleTest() {
    // TODO: test example
  }

  /** Test the property 'language' */
  @Test
  void languageTest() {
    // TODO: test language
  }

  /** Test the property 'languageName' */
  @Test
  void languageNameTest() {
    // TODO: test languageName
  }

  /** Test the property 'countryName' */
  @Test
  void countryNameTest() {
    // TODO: test countryName
  }
}
