/*
 * BIM-Portal REST-API
 * Dies ist die Dokumentation der REST-Endpunkte, die sowohl öffentliche als auch private Informationselemente abrufen können. Authentifizierung ist für den Zugriff auf private Ressourcen erforderlich. Die Endpunkte können auf dieser Seite getestet werden.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.bimportal.client.model;

import org.junit.jupiter.api.Test;

/** Model tests for FilterForPublicDto */
class FilterForPublicDtoTest {
  private final FilterForPublicDto model = new FilterForPublicDto();

  /** Model tests for FilterForPublicDto */
  @Test
  void testFilterForPublicDto() {
    // TODO: test FilterForPublicDto
  }

  /** Test the property 'name' */
  @Test
  void nameTest() {
    // TODO: test name
  }

  /** Test the property 'guid' */
  @Test
  void guidTest() {
    // TODO: test guid
  }
}
