/*
 * BIM-Portal REST-API
 * Dies ist die Dokumentation der REST-Endpunkte, die sowohl öffentliche als auch private Informationselemente abrufen können. Authentifizierung ist für den Zugriff auf private Ressourcen erforderlich. Die Endpunkte können auf dieser Seite getestet werden.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.bimportal.client.model;

import org.junit.jupiter.api.Test;

/** Model tests for IFCDto */
class IFCDtoTest {
  private final IFCDto model = new IFCDto();

  /** Model tests for IFCDto */
  @Test
  void testIFCDto() {
    // TODO: test IFCDto
  }

  /** Test the property 'id' */
  @Test
  void idTest() {
    // TODO: test id
  }

  /** Test the property 'type' */
  @Test
  void typeTest() {
    // TODO: test type
  }

  /** Test the property 'atClass' */
  @Test
  void atClassTest() {
    // TODO: test atClass
  }

  /** Test the property 'ifcView' */
  @Test
  void ifcViewTest() {
    // TODO: test ifcView
  }

  /** Test the property 'ifcClass' */
  @Test
  void ifcClassTest() {
    // TODO: test ifcClass
  }

  /** Test the property 'ifcType' */
  @Test
  void ifcTypeTest() {
    // TODO: test ifcType
  }

  /** Test the property 'groupAsIFCePset' */
  @Test
  void groupAsIFCePsetTest() {
    // TODO: test groupAsIFCePset
  }

  /** Test the property 'saveObjectTypeAsProperty' */
  @Test
  void saveObjectTypeAsPropertyTest() {
    // TODO: test saveObjectTypeAsProperty
  }
}
