/*
 * BIM-Portal REST-API
 * Dies ist die Dokumentation der REST-Endpunkte, die sowohl öffentliche als auch private Informationselemente abrufen können. Authentifizierung ist für den Zugriff auf private Ressourcen erforderlich. Die Endpunkte können auf dieser Seite getestet werden.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.bimportal.client.model;

import org.junit.jupiter.api.Test;

/** Model tests for JWTTokenPublicDto */
class JWTTokenPublicDtoTest {
  private final JWTTokenPublicDto model = new JWTTokenPublicDto();

  /** Model tests for JWTTokenPublicDto */
  @Test
  void testJWTTokenPublicDto() {
    // TODO: test JWTTokenPublicDto
  }

  /** Test the property 'token' */
  @Test
  void tokenTest() {
    // TODO: test token
  }

  /** Test the property 'refreshToken' */
  @Test
  void refreshTokenTest() {
    // TODO: test refreshToken
  }

  /** Test the property 'validTill' */
  @Test
  void validTillTest() {
    // TODO: test validTill
  }
}
