/*
 * BIM-Portal REST-API
 * Dies ist die Dokumentation der REST-Endpunkte, die sowohl öffentliche als auch private Informationselemente abrufen können. Authentifizierung ist für den Zugriff auf private Ressourcen erforderlich. Die Endpunkte können auf dieser Seite getestet werden.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.bimportal.client.model;

import org.junit.jupiter.api.Test;

/** Model tests for OKSTRADto */
class OKSTRADtoTest {
  private final OKSTRADto model = new OKSTRADto();

  /** Model tests for OKSTRADto */
  @Test
  void testOKSTRADto() {
    // TODO: test OKSTRADto
  }

  /** Test the property 'id' */
  @Test
  void idTest() {
    // TODO: test id
  }

  /** Test the property 'type' */
  @Test
  void typeTest() {
    // TODO: test type
  }

  /** Test the property 'atClass' */
  @Test
  void atClassTest() {
    // TODO: test atClass
  }

  /** Test the property 'fileId' */
  @Test
  void fileIdTest() {
    // TODO: test fileId
  }

  /** Test the property 'fileName' */
  @Test
  void fileNameTest() {
    // TODO: test fileName
  }

  /** Test the property 'name' */
  @Test
  void nameTest() {
    // TODO: test name
  }
}
