/*
 * BIM-Portal REST-API
 * Dies ist die Dokumentation der REST-Endpunkte, die sowohl öffentliche als auch private Informationselemente abrufen können. Authentifizierung ist für den Zugriff auf private Ressourcen erforderlich. Die Endpunkte können auf dieser Seite getestet werden.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bimportal.client.model;

import com.bimportal.client.model.DataFormatDto;
import com.bimportal.client.model.DataFormatTypeDto;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.UUID;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OtherDto
 */
class OtherDtoTest {
    private final OtherDto model = new OtherDto();

    /**
     * Model tests for OtherDto
     */
    @Test
    void testOtherDto() {
        // TODO: test OtherDto
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'atClass'
     */
    @Test
    void atClassTest() {
        // TODO: test atClass
    }

    /**
     * Test the property 'dataFormatVersion'
     */
    @Test
    void dataFormatVersionTest() {
        // TODO: test dataFormatVersion
    }

    /**
     * Test the property 'viewType'
     */
    @Test
    void viewTypeTest() {
        // TODO: test viewType
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

}
