/*
 * BIM-Portal REST-API
 * Dies ist die Dokumentation der REST-Endpunkte, die sowohl öffentliche als auch private Informationselemente abrufen können. Authentifizierung ist für den Zugriff auf private Ressourcen erforderlich. Die Endpunkte können auf dieser Seite getestet werden.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.bimportal.client.model;

import org.junit.jupiter.api.Test;

/** Model tests for PhysicalQuantity */
class PhysicalQuantityTest {
  private final PhysicalQuantity model = new PhysicalQuantity();

  /** Model tests for PhysicalQuantity */
  @Test
  void testPhysicalQuantity() {
    // TODO: test PhysicalQuantity
  }

  /** Test the property 'id' */
  @Test
  void idTest() {
    // TODO: test id
  }

  /** Test the property 'version' */
  @Test
  void versionTest() {
    // TODO: test version
  }

  /** Test the property 'createdDate' */
  @Test
  void createdDateTest() {
    // TODO: test createdDate
  }

  /** Test the property 'siUnit' */
  @Test
  void siUnitTest() {
    // TODO: test siUnit
  }

  /** Test the property 'language' */
  @Test
  void languageTest() {
    // TODO: test language
  }
}
