/*
 * BIM-Portal REST-API
 * Dies ist die Dokumentation der REST-Endpunkte, die sowohl öffentliche als auch private Informationselemente abrufen können. Authentifizierung ist für den Zugriff auf private Ressourcen erforderlich. Die Endpunkte können auf dieser Seite getestet werden.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bimportal.client.model;

import com.bimportal.client.model.NamesInLanguageDto;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PropertyOrGroupWithNamesInLanguage
 */
class PropertyOrGroupWithNamesInLanguageTest {
    private final PropertyOrGroupWithNamesInLanguage model = new PropertyOrGroupWithNamesInLanguage();

    /**
     * Model tests for PropertyOrGroupWithNamesInLanguage
     */
    @Test
    void testPropertyOrGroupWithNamesInLanguage() {
        // TODO: test PropertyOrGroupWithNamesInLanguage
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'namesInLanguage'
     */
    @Test
    void namesInLanguageTest() {
        // TODO: test namesInLanguage
    }

    /**
     * Test the property 'versionNumber'
     */
    @Test
    void versionNumberTest() {
        // TODO: test versionNumber
    }

    /**
     * Test the property 'revisionNumber'
     */
    @Test
    void revisionNumberTest() {
        // TODO: test revisionNumber
    }

    /**
     * Test the property 'informationElementStatus'
     */
    @Test
    void informationElementStatusTest() {
        // TODO: test informationElementStatus
    }

}
