/*
 * BIM-Portal REST-API
 * Dies ist die Dokumentation der REST-Endpunkte, die sowohl öffentliche als auch private Informationselemente abrufen können. Authentifizierung ist für den Zugriff auf private Ressourcen erforderlich. Die Endpunkte können auf dieser Seite getestet werden.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.bimportal.client.model;

import org.junit.jupiter.api.Test;

/** Model tests for PropertyOrGroupForPublicDto */
class PropertyOrGroupForPublicDtoTest {
  private final PropertyOrGroupForPublicDto model = new PropertyOrGroupForPublicDto();

  /** Model tests for PropertyOrGroupForPublicDto */
  @Test
  void testPropertyOrGroupForPublicDto() {
    // TODO: test PropertyOrGroupForPublicDto
  }

  /** Test the property 'name' */
  @Test
  void nameTest() {
    // TODO: test name
  }

  /** Test the property 'definition' */
  @Test
  void definitionTest() {
    // TODO: test definition
  }

  /** Test the property 'guid' */
  @Test
  void guidTest() {
    // TODO: test guid
  }

  /** Test the property 'versionNumber' */
  @Test
  void versionNumberTest() {
    // TODO: test versionNumber
  }

  /** Test the property 'revisionNumber' */
  @Test
  void revisionNumberTest() {
    // TODO: test revisionNumber
  }

  /** Test the property 'parentGuids' */
  @Test
  void parentGuidsTest() {
    // TODO: test parentGuids
  }

  /** Test the property 'organisationName' */
  @Test
  void organisationNameTest() {
    // TODO: test organisationName
  }

  /** Test the property 'dataType' */
  @Test
  void dataTypeTest() {
    // TODO: test dataType
  }

  /** Test the property 'units' */
  @Test
  void unitsTest() {
    // TODO: test units
  }

  /** Test the property 'category' */
  @Test
  void categoryTest() {
    // TODO: test category
  }

  /** Test the property 'deprecated' */
  @Test
  void deprecatedTest() {
    // TODO: test deprecated
  }

  /** Test the property 'currentPage' */
  @Test
  void currentPageTest() {
    // TODO: test currentPage
  }

  /** Test the property 'maxPage' */
  @Test
  void maxPageTest() {
    // TODO: test maxPage
  }

  /** Test the property 'catalogInformation' */
  @Test
  void catalogInformationTest() {
    // TODO: test catalogInformation
  }
}
