/*
 * BIM-Portal REST-API
 * Dies ist die Dokumentation der REST-Endpunkte, die sowohl öffentliche als auch private Informationselemente abrufen können. Authentifizierung ist für den Zugriff auf private Ressourcen erforderlich. Die Endpunkte können auf dieser Seite getestet werden.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.bimportal.client.model;

import org.junit.jupiter.api.Test;

/** Model tests for RefreshTokenRequestDTO */
class RefreshTokenRequestDTOTest {
  private final RefreshTokenRequestDTO model = new RefreshTokenRequestDTO();

  /** Model tests for RefreshTokenRequestDTO */
  @Test
  void testRefreshTokenRequestDTO() {
    // TODO: test RefreshTokenRequestDTO
  }

  /** Test the property 'refreshToken' */
  @Test
  void refreshTokenTest() {
    // TODO: test refreshToken
  }
}
