/*
 * BIM-Portal REST-API
 * Dies ist die Dokumentation der REST-Endpunkte, die sowohl öffentliche als auch private Informationselemente abrufen können. Authentifizierung ist für den Zugriff auf private Ressourcen erforderlich. Die Endpunkte können auf dieser Seite getestet werden.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.bimportal.client.model;

import org.junit.jupiter.api.Test;

/** Model tests for SimpleDomainSpecificModelPublicDto */
class SimpleDomainSpecificModelPublicDtoTest {
  private final SimpleDomainSpecificModelPublicDto model = new SimpleDomainSpecificModelPublicDto();

  /** Model tests for SimpleDomainSpecificModelPublicDto */
  @Test
  void testSimpleDomainSpecificModelPublicDto() {
    // TODO: test SimpleDomainSpecificModelPublicDto
  }

  /** Test the property 'name' */
  @Test
  void nameTest() {
    // TODO: test name
  }

  /** Test the property 'dataFormats' */
  @Test
  void dataFormatsTest() {
    // TODO: test dataFormats
  }

  /** Test the property 'description' */
  @Test
  void descriptionTest() {
    // TODO: test description
  }

  /** Test the property 'id' */
  @Test
  void idTest() {
    // TODO: test id
  }

  /** Test the property 'guid' */
  @Test
  void guidTest() {
    // TODO: test guid
  }

  /** Test the property 'version' */
  @Test
  void versionTest() {
    // TODO: test version
  }

  /** Test the property 'organisation' */
  @Test
  void organisationTest() {
    // TODO: test organisation
  }

  /** Test the property 'visibility' */
  @Test
  void visibilityTest() {
    // TODO: test visibility
  }

  /** Test the property 'constructionTypes' */
  @Test
  void constructionTypesTest() {
    // TODO: test constructionTypes
  }

  /** Test the property 'projectPhases' */
  @Test
  void projectPhasesTest() {
    // TODO: test projectPhases
  }

  /** Test the property 'purposes' */
  @Test
  void purposesTest() {
    // TODO: test purposes
  }

  /** Test the property 'actors' */
  @Test
  void actorsTest() {
    // TODO: test actors
  }

  /** Test the property 'domainSpecificModelTypes' */
  @Test
  void domainSpecificModelTypesTest() {
    // TODO: test domainSpecificModelTypes
  }

  /** Test the property 'filters' */
  @Test
  void filtersTest() {
    // TODO: test filters
  }
}
