/*
 * BIM-Portal REST-API
 * Dies ist die Dokumentation der REST-Endpunkte, die sowohl öffentliche als auch private Informationselemente abrufen können. Authentifizierung ist für den Zugriff auf private Ressourcen erforderlich. Die Endpunkte können auf dieser Seite getestet werden.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bimportal.client.model;

import com.bimportal.client.model.NamesInLanguage;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.UUID;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SimpleInheritedPropertyDto
 */
class SimpleInheritedPropertyDtoTest {
    private final SimpleInheritedPropertyDto model = new SimpleInheritedPropertyDto();

    /**
     * Model tests for SimpleInheritedPropertyDto
     */
    @Test
    void testSimpleInheritedPropertyDto() {
        // TODO: test SimpleInheritedPropertyDto
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'names'
     */
    @Test
    void namesTest() {
        // TODO: test names
    }

    /**
     * Test the property 'versionNumber'
     */
    @Test
    void versionNumberTest() {
        // TODO: test versionNumber
    }

    /**
     * Test the property 'revisionNumber'
     */
    @Test
    void revisionNumberTest() {
        // TODO: test revisionNumber
    }

    /**
     * Test the property 'informationElementStatus'
     */
    @Test
    void informationElementStatusTest() {
        // TODO: test informationElementStatus
    }

}
