/*
 * BIM-Portal REST-API
 * Dies ist die Dokumentation der REST-Endpunkte, die sowohl öffentliche als auch private Informationselemente abrufen können. Authentifizierung ist für den Zugriff auf private Ressourcen erforderlich. Die Endpunkte können auf dieser Seite getestet werden.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bimportal.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UserLoginPublicDto
 */
class UserLoginPublicDtoTest {
    private final UserLoginPublicDto model = new UserLoginPublicDto();

    /**
     * Model tests for UserLoginPublicDto
     */
    @Test
    void testUserLoginPublicDto() {
        // TODO: test UserLoginPublicDto
    }

    /**
     * Test the property 'mail'
     */
    @Test
    void mailTest() {
        // TODO: test mail
    }

    /**
     * Test the property 'password'
     */
    @Test
    void passwordTest() {
        // TODO: test password
    }

}
